### ISSUE TITLE
Problem with applying topk

### ISSUE THREAD

**Issue by dkdl012** [addb-swstarlab/RocksDB-Optimization-wDNN#1]
Hi, thanks to provide tuning code on RocksDB.

I wonder how i can prune knobs with topk. When I changed "--topk" to some numeric number which is a role of parser, the knob data is changed weird. As the result, final solution data is not matched with columns.

**Comment by addb-swstarlab** [comment]
Sorry for the late reply.
We'll check where the issue occurs and update as soon as possible.

Thanks you for pointing out the issue.

**Comment by addb-swstarlab** [comment]
We found a problem and fixed it.
See line 517 at models/step.py
