### ISSUE TITLE
Question about data with Mahalanobis distance

### ISSUE THREAD

**Issue by Ychanho** [addb-swstarlab/RocksDB-Optimization-wDNN#3]
I have a question.
Why did you compare the data in terms of Mahalanobis distance? 
Is there any distance candidate other than Mahalanobis?

**Comment by ChoJunHeum** [comment]
As far as I know, there are many types of workload. Then, is this tuning method possible to tune accordingly no matter what kind of workload comes? And may I know additional information about the dataset?
