### ISSUE TITLE
Dataset Access Request: 20,000 Random Configurations and 16 Workloads

### ISSUE THREAD

**Issue by jeongeunKim-art** [addb-swstarlab/RocksDB-Optimization-wDNN#5]
Hello,
I am a user with a keen interest in RTune.  According to the README document, the dataset for tuning RocksDB parameters consists of 20,000 random configurations and 16 different workloads. I believe this dataset would be extremely useful for performance analysis and research.

Is there a way to access this dataset? Alternatively, would it be possible for you to share the dataset directly? I would like to use it to advance my research.

Thank you!

**Comment by huijunjin** [comment]
Thank you for your interest in my dataset. Before sharing it, I would like to confirm that your research topic is closely related to mine. Once verified, I will be happy to send it to you via email.
Email: jinhuijun@yonsei.ac.kr
