### ISSUE TITLE
Request for Papers Related to Your work

### ISSUE THREAD

**Issue by HwanheeKim813** [addb-swstarlab/RocksDB-Optimization-wDNN#6]
Hello,

Thank you for sharing this code! I am very interested in learning more about the research behind it. Could you let me know if this work is associated with a specific research paper or publication? If so, could you kindly provide the citation or a link to the paper?

**Comment by huijunjin** [comment]
Thank you for your interest! The design of this pipeline draws inspiration from OtterTune, a machine learning-based system for automatic tuning of database management systems (DBMS). OtterTune optimizes configurations by analyzing performance metrics from previous sessions and refining them through iterations. We extended this concept by incorporating a genetic algorithm to enhance the search for optimal configurations efficiently.

For more details, you can refer to OtterTune’s SIGMOD 2017 paper, "Automatic Database Management System Tuning Through Large-scale Machine Learning," which showcases its approach to tuning MySQL and PostgreSQL databases with minimal human intervention.
